//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMPLETE_FLAT_UI.ServicioPerfiles {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Perfiles", Namespace="http://schemas.datacontract.org/2004/07/FeriaVirtualServices.Structures.Tables")]
    [System.SerializableAttribute()]
    public partial class Perfiles : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_perfilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_perfil {
            get {
                return this.Id_perfilField;
            }
            set {
                if ((this.Id_perfilField.Equals(value) != true)) {
                    this.Id_perfilField = value;
                    this.RaisePropertyChanged("Id_perfil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioPerfiles.IServicePerfiles")]
    public interface IServicePerfiles {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePerfiles/GetPerfiles", ReplyAction="http://tempuri.org/IServicePerfiles/GetPerfilesResponse")]
        COMPLETE_FLAT_UI.ServicioPerfiles.Perfiles[] GetPerfiles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePerfiles/GetPerfiles", ReplyAction="http://tempuri.org/IServicePerfiles/GetPerfilesResponse")]
        System.Threading.Tasks.Task<COMPLETE_FLAT_UI.ServicioPerfiles.Perfiles[]> GetPerfilesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicePerfilesChannel : COMPLETE_FLAT_UI.ServicioPerfiles.IServicePerfiles, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicePerfilesClient : System.ServiceModel.ClientBase<COMPLETE_FLAT_UI.ServicioPerfiles.IServicePerfiles>, COMPLETE_FLAT_UI.ServicioPerfiles.IServicePerfiles {
        
        public ServicePerfilesClient() {
        }
        
        public ServicePerfilesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicePerfilesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicePerfilesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicePerfilesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public COMPLETE_FLAT_UI.ServicioPerfiles.Perfiles[] GetPerfiles() {
            return base.Channel.GetPerfiles();
        }
        
        public System.Threading.Tasks.Task<COMPLETE_FLAT_UI.ServicioPerfiles.Perfiles[]> GetPerfilesAsync() {
            return base.Channel.GetPerfilesAsync();
        }
    }
}
