//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMPLETE_FLAT_UI.ServicioOfertas {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ofertas", Namespace="http://schemas.datacontract.org/2004/07/FeriaVirtualServices.Structures.Tables")]
    [System.SerializableAttribute()]
    public partial class Ofertas : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fecha_inicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_ofertaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_ventaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha_inicio {
            get {
                return this.Fecha_inicioField;
            }
            set {
                if ((this.Fecha_inicioField.Equals(value) != true)) {
                    this.Fecha_inicioField = value;
                    this.RaisePropertyChanged("Fecha_inicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_oferta {
            get {
                return this.Id_ofertaField;
            }
            set {
                if ((this.Id_ofertaField.Equals(value) != true)) {
                    this.Id_ofertaField = value;
                    this.RaisePropertyChanged("Id_oferta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_venta {
            get {
                return this.Id_ventaField;
            }
            set {
                if ((this.Id_ventaField.Equals(value) != true)) {
                    this.Id_ventaField = value;
                    this.RaisePropertyChanged("Id_venta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioOfertas.IServiceOfertas")]
    public interface IServiceOfertas {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOfertas/GetOfertas", ReplyAction="http://tempuri.org/IServiceOfertas/GetOfertasResponse")]
        COMPLETE_FLAT_UI.ServicioOfertas.Ofertas[] GetOfertas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOfertas/GetOfertas", ReplyAction="http://tempuri.org/IServiceOfertas/GetOfertasResponse")]
        System.Threading.Tasks.Task<COMPLETE_FLAT_UI.ServicioOfertas.Ofertas[]> GetOfertasAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceOfertasChannel : COMPLETE_FLAT_UI.ServicioOfertas.IServiceOfertas, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceOfertasClient : System.ServiceModel.ClientBase<COMPLETE_FLAT_UI.ServicioOfertas.IServiceOfertas>, COMPLETE_FLAT_UI.ServicioOfertas.IServiceOfertas {
        
        public ServiceOfertasClient() {
        }
        
        public ServiceOfertasClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceOfertasClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOfertasClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOfertasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public COMPLETE_FLAT_UI.ServicioOfertas.Ofertas[] GetOfertas() {
            return base.Channel.GetOfertas();
        }
        
        public System.Threading.Tasks.Task<COMPLETE_FLAT_UI.ServicioOfertas.Ofertas[]> GetOfertasAsync() {
            return base.Channel.GetOfertasAsync();
        }
    }
}
