//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMPLETE_FLAT_UI.ServicioAcciones {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/FeriaVirtualServices.Structures.Tables")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PerfilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido {
            get {
                return this.ApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoField, value) != true)) {
                    this.ApellidoField = value;
                    this.RaisePropertyChanged("Apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaCreacion {
            get {
                return this.FechaCreacionField;
            }
            set {
                if ((this.FechaCreacionField.Equals(value) != true)) {
                    this.FechaCreacionField = value;
                    this.RaisePropertyChanged("FechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Perfil {
            get {
                return this.PerfilField;
            }
            set {
                if ((object.ReferenceEquals(this.PerfilField, value) != true)) {
                    this.PerfilField = value;
                    this.RaisePropertyChanged("Perfil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioAcciones.IServiceAcciones")]
    public interface IServiceAcciones {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAcciones/AdjudicarProductor", ReplyAction="http://tempuri.org/IServiceAcciones/AdjudicarProductorResponse")]
        COMPLETE_FLAT_UI.ServicioAcciones.Usuario AdjudicarProductor(int idVenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAcciones/AdjudicarProductor", ReplyAction="http://tempuri.org/IServiceAcciones/AdjudicarProductorResponse")]
        System.Threading.Tasks.Task<COMPLETE_FLAT_UI.ServicioAcciones.Usuario> AdjudicarProductorAsync(int idVenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAcciones/AdjudicarTransportista", ReplyAction="http://tempuri.org/IServiceAcciones/AdjudicarTransportistaResponse")]
        COMPLETE_FLAT_UI.ServicioAcciones.Usuario AdjudicarTransportista(int idVenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAcciones/AdjudicarTransportista", ReplyAction="http://tempuri.org/IServiceAcciones/AdjudicarTransportistaResponse")]
        System.Threading.Tasks.Task<COMPLETE_FLAT_UI.ServicioAcciones.Usuario> AdjudicarTransportistaAsync(int idVenta);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceAccionesChannel : COMPLETE_FLAT_UI.ServicioAcciones.IServiceAcciones, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceAccionesClient : System.ServiceModel.ClientBase<COMPLETE_FLAT_UI.ServicioAcciones.IServiceAcciones>, COMPLETE_FLAT_UI.ServicioAcciones.IServiceAcciones {
        
        public ServiceAccionesClient() {
        }
        
        public ServiceAccionesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceAccionesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceAccionesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceAccionesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public COMPLETE_FLAT_UI.ServicioAcciones.Usuario AdjudicarProductor(int idVenta) {
            return base.Channel.AdjudicarProductor(idVenta);
        }
        
        public System.Threading.Tasks.Task<COMPLETE_FLAT_UI.ServicioAcciones.Usuario> AdjudicarProductorAsync(int idVenta) {
            return base.Channel.AdjudicarProductorAsync(idVenta);
        }
        
        public COMPLETE_FLAT_UI.ServicioAcciones.Usuario AdjudicarTransportista(int idVenta) {
            return base.Channel.AdjudicarTransportista(idVenta);
        }
        
        public System.Threading.Tasks.Task<COMPLETE_FLAT_UI.ServicioAcciones.Usuario> AdjudicarTransportistaAsync(int idVenta) {
            return base.Channel.AdjudicarTransportistaAsync(idVenta);
        }
    }
}
