//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMPLETE_FLAT_UI.ServiciosUsuarios {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/FeriaVirtualServices.Structures.Tables")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PerfilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido {
            get {
                return this.ApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoField, value) != true)) {
                    this.ApellidoField = value;
                    this.RaisePropertyChanged("Apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaCreacion {
            get {
                return this.FechaCreacionField;
            }
            set {
                if ((this.FechaCreacionField.Equals(value) != true)) {
                    this.FechaCreacionField = value;
                    this.RaisePropertyChanged("FechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Perfil {
            get {
                return this.PerfilField;
            }
            set {
                if ((object.ReferenceEquals(this.PerfilField, value) != true)) {
                    this.PerfilField = value;
                    this.RaisePropertyChanged("Perfil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiciosUsuarios.IUsuarios")]
    public interface IUsuarios {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/Login", ReplyAction="http://tempuri.org/IUsuarios/LoginResponse")]
        string Login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/Login", ReplyAction="http://tempuri.org/IUsuarios/LoginResponse")]
        System.Threading.Tasks.Task<string> LoginAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/GetUsuarios", ReplyAction="http://tempuri.org/IUsuarios/GetUsuariosResponse")]
        COMPLETE_FLAT_UI.ServiciosUsuarios.Usuario[] GetUsuarios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/GetUsuarios", ReplyAction="http://tempuri.org/IUsuarios/GetUsuariosResponse")]
        System.Threading.Tasks.Task<COMPLETE_FLAT_UI.ServiciosUsuarios.Usuario[]> GetUsuariosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/UpdateUsuario", ReplyAction="http://tempuri.org/IUsuarios/UpdateUsuarioResponse")]
        string UpdateUsuario(int id, string username, string password, int fk_perfil, string nombre, string apellido, string email, System.DateTime fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/UpdateUsuario", ReplyAction="http://tempuri.org/IUsuarios/UpdateUsuarioResponse")]
        System.Threading.Tasks.Task<string> UpdateUsuarioAsync(int id, string username, string password, int fk_perfil, string nombre, string apellido, string email, System.DateTime fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/InsertUsuario", ReplyAction="http://tempuri.org/IUsuarios/InsertUsuarioResponse")]
        string InsertUsuario(string username, string password, int id_perfil, string nombre, string apellido, string email, System.DateTime fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/InsertUsuario", ReplyAction="http://tempuri.org/IUsuarios/InsertUsuarioResponse")]
        System.Threading.Tasks.Task<string> InsertUsuarioAsync(string username, string password, int id_perfil, string nombre, string apellido, string email, System.DateTime fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/DeleteUsuario", ReplyAction="http://tempuri.org/IUsuarios/DeleteUsuarioResponse")]
        string DeleteUsuario(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/DeleteUsuario", ReplyAction="http://tempuri.org/IUsuarios/DeleteUsuarioResponse")]
        System.Threading.Tasks.Task<string> DeleteUsuarioAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUsuariosChannel : COMPLETE_FLAT_UI.ServiciosUsuarios.IUsuarios, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsuariosClient : System.ServiceModel.ClientBase<COMPLETE_FLAT_UI.ServiciosUsuarios.IUsuarios>, COMPLETE_FLAT_UI.ServiciosUsuarios.IUsuarios {
        
        public UsuariosClient() {
        }
        
        public UsuariosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsuariosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuariosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuariosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Login(string username, string password) {
            return base.Channel.Login(username, password);
        }
        
        public System.Threading.Tasks.Task<string> LoginAsync(string username, string password) {
            return base.Channel.LoginAsync(username, password);
        }
        
        public COMPLETE_FLAT_UI.ServiciosUsuarios.Usuario[] GetUsuarios() {
            return base.Channel.GetUsuarios();
        }
        
        public System.Threading.Tasks.Task<COMPLETE_FLAT_UI.ServiciosUsuarios.Usuario[]> GetUsuariosAsync() {
            return base.Channel.GetUsuariosAsync();
        }
        
        public string UpdateUsuario(int id, string username, string password, int fk_perfil, string nombre, string apellido, string email, System.DateTime fecha) {
            return base.Channel.UpdateUsuario(id, username, password, fk_perfil, nombre, apellido, email, fecha);
        }
        
        public System.Threading.Tasks.Task<string> UpdateUsuarioAsync(int id, string username, string password, int fk_perfil, string nombre, string apellido, string email, System.DateTime fecha) {
            return base.Channel.UpdateUsuarioAsync(id, username, password, fk_perfil, nombre, apellido, email, fecha);
        }
        
        public string InsertUsuario(string username, string password, int id_perfil, string nombre, string apellido, string email, System.DateTime fecha) {
            return base.Channel.InsertUsuario(username, password, id_perfil, nombre, apellido, email, fecha);
        }
        
        public System.Threading.Tasks.Task<string> InsertUsuarioAsync(string username, string password, int id_perfil, string nombre, string apellido, string email, System.DateTime fecha) {
            return base.Channel.InsertUsuarioAsync(username, password, id_perfil, nombre, apellido, email, fecha);
        }
        
        public string DeleteUsuario(int id) {
            return base.Channel.DeleteUsuario(id);
        }
        
        public System.Threading.Tasks.Task<string> DeleteUsuarioAsync(int id) {
            return base.Channel.DeleteUsuarioAsync(id);
        }
    }
}
