//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMPLETE_FLAT_UI.ServicioContratos {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Contratos", Namespace="http://schemas.datacontract.org/2004/07/FeriaVirtualServices.Structures.Tables")]
    [System.SerializableAttribute()]
    public partial class Contratos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fecha_inicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fecha_terminoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_contratoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_usuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha_inicio {
            get {
                return this.Fecha_inicioField;
            }
            set {
                if ((this.Fecha_inicioField.Equals(value) != true)) {
                    this.Fecha_inicioField = value;
                    this.RaisePropertyChanged("Fecha_inicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha_termino {
            get {
                return this.Fecha_terminoField;
            }
            set {
                if ((this.Fecha_terminoField.Equals(value) != true)) {
                    this.Fecha_terminoField = value;
                    this.RaisePropertyChanged("Fecha_termino");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_contrato {
            get {
                return this.Id_contratoField;
            }
            set {
                if ((this.Id_contratoField.Equals(value) != true)) {
                    this.Id_contratoField = value;
                    this.RaisePropertyChanged("Id_contrato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_usuario {
            get {
                return this.Id_usuarioField;
            }
            set {
                if ((this.Id_usuarioField.Equals(value) != true)) {
                    this.Id_usuarioField = value;
                    this.RaisePropertyChanged("Id_usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioContratos.IServiceContratos")]
    public interface IServiceContratos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceContratos/GetContratos", ReplyAction="http://tempuri.org/IServiceContratos/GetContratosResponse")]
        COMPLETE_FLAT_UI.ServicioContratos.Contratos[] GetContratos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceContratos/GetContratos", ReplyAction="http://tempuri.org/IServiceContratos/GetContratosResponse")]
        System.Threading.Tasks.Task<COMPLETE_FLAT_UI.ServicioContratos.Contratos[]> GetContratosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceContratos/UpdateVenta", ReplyAction="http://tempuri.org/IServiceContratos/UpdateVentaResponse")]
        string UpdateVenta(int id, System.DateTime fecha_inicio, System.DateTime fecha_termino);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceContratos/UpdateVenta", ReplyAction="http://tempuri.org/IServiceContratos/UpdateVentaResponse")]
        System.Threading.Tasks.Task<string> UpdateVentaAsync(int id, System.DateTime fecha_inicio, System.DateTime fecha_termino);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceContratos/InsertContrato", ReplyAction="http://tempuri.org/IServiceContratos/InsertContratoResponse")]
        string InsertContrato(int id_usuario, System.DateTime fecha_inicio, System.DateTime fecha_termino);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceContratos/InsertContrato", ReplyAction="http://tempuri.org/IServiceContratos/InsertContratoResponse")]
        System.Threading.Tasks.Task<string> InsertContratoAsync(int id_usuario, System.DateTime fecha_inicio, System.DateTime fecha_termino);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceContratos/DeleteContrato", ReplyAction="http://tempuri.org/IServiceContratos/DeleteContratoResponse")]
        string DeleteContrato(int id_contrato);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceContratos/DeleteContrato", ReplyAction="http://tempuri.org/IServiceContratos/DeleteContratoResponse")]
        System.Threading.Tasks.Task<string> DeleteContratoAsync(int id_contrato);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceContratosChannel : COMPLETE_FLAT_UI.ServicioContratos.IServiceContratos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceContratosClient : System.ServiceModel.ClientBase<COMPLETE_FLAT_UI.ServicioContratos.IServiceContratos>, COMPLETE_FLAT_UI.ServicioContratos.IServiceContratos {
        
        public ServiceContratosClient() {
        }
        
        public ServiceContratosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceContratosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceContratosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceContratosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public COMPLETE_FLAT_UI.ServicioContratos.Contratos[] GetContratos() {
            return base.Channel.GetContratos();
        }
        
        public System.Threading.Tasks.Task<COMPLETE_FLAT_UI.ServicioContratos.Contratos[]> GetContratosAsync() {
            return base.Channel.GetContratosAsync();
        }
        
        public string UpdateVenta(int id, System.DateTime fecha_inicio, System.DateTime fecha_termino) {
            return base.Channel.UpdateVenta(id, fecha_inicio, fecha_termino);
        }
        
        public System.Threading.Tasks.Task<string> UpdateVentaAsync(int id, System.DateTime fecha_inicio, System.DateTime fecha_termino) {
            return base.Channel.UpdateVentaAsync(id, fecha_inicio, fecha_termino);
        }
        
        public string InsertContrato(int id_usuario, System.DateTime fecha_inicio, System.DateTime fecha_termino) {
            return base.Channel.InsertContrato(id_usuario, fecha_inicio, fecha_termino);
        }
        
        public System.Threading.Tasks.Task<string> InsertContratoAsync(int id_usuario, System.DateTime fecha_inicio, System.DateTime fecha_termino) {
            return base.Channel.InsertContratoAsync(id_usuario, fecha_inicio, fecha_termino);
        }
        
        public string DeleteContrato(int id_contrato) {
            return base.Channel.DeleteContrato(id_contrato);
        }
        
        public System.Threading.Tasks.Task<string> DeleteContratoAsync(int id_contrato) {
            return base.Channel.DeleteContratoAsync(id_contrato);
        }
    }
}
